### ISSUE TITLE
O que acha de configurar o rustfmt de forma mais especifica?

### ISSUE THREAD

**Issue by GChicha** [theosirian/nanilang#2]
```toml
max_width = 80
tab_spaces = 4
report_todo = "Unnumbered"
report_fixme = "Unnumbered" 
trailing_comma = "Always"
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
```

Só tem de observar que o vim-autoformat não é exatamente compativel tem de colocar umas opções no vimrc para ficar massa

```vim
let g:autoformat_autoindent = 0
let g:autoformat_retab = 0
let g:autoformat_remove_trailing_spaces = 0
```
